#!/bin/bash

echo "🚀 TIPM Production Deployment Script"
echo "====================================="
echo ""

echo "📋 Pre-deployment checklist:"
echo "✅ Code pushed to GitHub"
echo "✅ CORS configuration fixed"
echo "✅ Environment variables configured"
echo "✅ Deployment files created"
echo ""

echo "🔧 Step 1: Deploy Backend to Render"
echo "-----------------------------------"
echo "1. Go to https://render.com"
echo "2. Sign in/Sign up"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect your GitHub repository: thegeekybeng/TIPM"
echo "5. Configure the service:"
echo "   - Name: tipm-api"
echo "   - Root Directory: api/"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: python -m uvicorn main:app --host=0.0.0.0 --port=10000"
echo "   - Plan: Free"
echo "6. Add Environment Variables:"
echo "   - PYTHON_VERSION: 3.11.9"
echo "   - ENVIRONMENT: production"
echo "7. Click 'Create Web Service'"
echo ""

echo "🌐 Step 2: Deploy Frontend to Vercel"
echo "-------------------------------------"
echo "1. Go to https://vercel.com"
echo "2. Sign in/Sign up"
echo "3. Click 'New Project'"
echo "4. Import your GitHub repository: thegeekybeng/TIPM"
echo "5. Configure the project:"
echo "   - Framework Preset: Next.js"
echo "   - Root Directory: . (root)"
echo "6. Add Environment Variables:"
echo "   - NEXT_PUBLIC_API_BASE: https://tipm-api.onrender.com"
echo "   - ENVIRONMENT: production"
echo "   - NODE_ENV: production"
echo "7. Click 'Deploy'"
echo ""

echo "🧪 Step 3: Test Production Deployment"
echo "-------------------------------------"
echo "Once both are deployed, test with:"
echo ""
echo "# Test backend health"
echo "curl https://tipm-api.onrender.com/health"
echo ""
echo "# Test frontend"
echo "curl https://tipm-app.vercel.app"
echo ""
echo "# Test CORS between production domains"
echo "curl -H 'Origin: https://tipm-app.vercel.app' \\"
echo "     -H 'Access-Control-Request-Method: GET' \\"
echo "     -X OPTIONS https://tipm-api.onrender.com/health"
echo ""

echo "⏱️  Estimated deployment time: 15-30 minutes"
echo "📱 Monitor progress in Render and Vercel dashboards"
echo ""
echo "🎯 Good luck with your deployment!"
