[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python build complete'"]

[start]
cmd = "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"
