[phases.setup]
nixPkgs = [
  "python310", 
  "python310Packages.fastapi", 
  "python310Packages.uvicorn", 
  "python310Packages.pandas", 
  "python310Packages.openpyxl"
]

[phases.build]
cmds = ["echo 'Python build complete'"]

[start]
cmd = "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"
